version: "3.9"
services:
  app:
    container_name: osome-interview
    command: sh -c "npm run start:prod"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .dev.env
    depends_on:
      - postgres
    networks:
      - osome-network

  postgres:
    container_name: osome-postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .dev.env
    networks:
      - osome-network

networks:
  osome-network:
    external: true
